name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: lint
      run: |
       test -z $(gofmt -l .)
       go vet
       
    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build -v ./...
